# This is a basic workflow to help you get started with Actions
# workflow_dispatch
name: CI

on: [push, pull_request]
#
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-root: '.'
        flake8-flags: ''
        mypy-flags: ''
        fail-on-isort: true
