## if [ -d tests ] || [ -d test ]; then python -m pytest; fi
# if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
      
        
    - name: linting
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-root: '.'
        flake8-flags: ''
        

    - name: Test with pytest
      run: |
        python -m pytest